### ISSUE TITLE
About Multiple GPU's Training Support

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava-dl#59]
Objective of issue: 
Helllo,
I am curious about how one can train a network in SLAYER with the support of multiple GPU's.
 I simply tried adding the lines  `net= torch.nn.DataParallel(net)   net.to(device)` . in standard NMNIST notebook, but it did not work after first epoch.

 Is or Will there be any slayer adaptation of multi GPUs  training support ?

If one can use the multi GPU training utilities in PyTorch how it should be set in order not to crash ? 

Sincerely,

**Lava DL version:**

- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request
- [x] documentation request

**Current behavior:**

- 

**Expected behavior:**

- 

**Steps to reproduce:**

- 

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by Barchid** [comment]
I am wondering: what kind of error do you have after this first epoch?

If this is related to `slayers.utils.Assistant`, I made a small project that uses `pytorch-lightning` instead of the default Assistant. You can try the built-in multi-gpu support of Lightning instead of the Assistant, you might be luckier with it.

The project: https://github.com/Barchid/lava-dl-lightning . For the moment, I made it work with the PilotNet-SDNN example but normally, the LightingModule should work with an SNN.

**Comment by ahmetakman** [comment]
Yeah, I saw the discussion topic you have opened. Congratulations on the effort.  I will consider your suggestion, but I am curious about a more native solution in lava-dl. Of course, one can also utilize multiple GPUs feature of some other libraries. I am wondering if there are any plans of adding (or adapting) such a feature so that it would be scalable to all SNNs (Slayer defined). This is a point that I could not see in any Intel document. 
I think these kinds of simple enhancements are important to encourage someone who is looking for deployable features of the lava-loihi ecosystem.

**Comment by Barchid** [comment]
Thank you for your consideration :smile: 

If I understood well the philisophy of Lava-DL, the whole `slayer` module is a pytorch wrapper to perform some offline training before deploying a network in the Loihi using `netx`. In that fashion, using any other pytorch library should work, as long as the exported neural net can be deployed on neuromorphic hardware.

I don't know if there is any plan on creating more specific features for the lava-loihi ecosystem with `lava-dl`. But if that is the case, then you are right, using third-party libraries is not a good choice for the future. I hope the discussion topic will bring us some aswers about that.

Cheers!

**Comment by bamsumit** [comment]
@ahmetakman There is a quirk for running lava-dl slayer models with some neuron models due to the __automatic shape inferencing feature__ of lava-dl slayer. You may refer to this solution: https://github.com/lava-nc/lava-dl/issues/26

### Short explanation
Basically, we lava-dl slayer does not need the neuron layers to be defined with the correct shape. These shapes are identified on the first inference run based on their input. So when you try and run torch data-parallel on a network, this automatic shape identification happens on spawned processes which mismatch when torch data-parallel tries to consolidate parameters on the parent copy. Therefore you get errors after the first iteration.
